In [ ]:
import pandas as pd
import numpy as np

In [ ]:
tEmployees = pd.read_csv('tEmployees.csv')
tStores = pd.read_csv('tStores.csv')
tSales = pd.read_csv('tSales.csv')

In [ ]:
#aggregate function
# first we pick our grouping then we pick what to aggregate
# dataframename.groupby(specify the name of the grouping column).agg(
# name of the new column = (column upon which to aggregate, aggregation function)
# )
# aggregation functions include sum, count, min, max, mean, median

cityStores = tStores.groupby('City').agg(
    sumSqFt = ('SqFt', 'sum'),
    numStores = ('Store', 'count')
)

#1) tStores – count number of stores in each city, sum square footage. Filter for more than one store
cityStores.loc[cityStores['numStores']>1]

              sumSqFt  numStores
City
DONCASTER     34700.0          2
EANVERNESS    43300.0          3
GOULCREST     20500.0          2
HARDERSFIELD  12300.0          2
HORNSEY       28100.0          4
LARNWICK      18300.0          2
MOUNTMEND     68700.0          4

In [ ]:
prices_table = pd.read_csv('merge_prices.csv')
qty_table = pd.read_csv('merge_qty.csv')

In [ ]:
#2) Temployees – total number of employees by city > I will need to merge tStores to
# tEmployees to find the city each employee works in

#assign a variable so we can continue using it

cityEmployees = pd.merge(tEmployees, tStores, on='Store', how = 'left')

In [ ]:
# then aggregate total employees based on city
cityEmployees.groupby('City').agg(
    totalEmployees = ('emplID', 'count')
)

             totalEmployees
City
ABERDEEN                 13
AETHELNEY                11
ALNERWICK                11
ARBINGTON                18
ASHBORNE                 13
...                     ...
TYWARDREATH              19
VERITAS                   6
WANBORNE                 21
WINTERVALE                8
WOLFORD                   9

[67 rows x 1 columns]

In [ ]:
#3) tSales – merge with tStores to figure out which city each transaction took place in
Store_CitySales = pd.merge(tSales, tStores, on='Store', how = 'left')

In [ ]:
display(Store_CitySales)

,salesID,Store,Brand,SalesQuantity,SalesPrice,SalesDate,ExciseTax,City,County,SqFt
0,1,1,10021,1,12.99,2015-07-12,0.11,HARDERSFIELD,Baker County,8300.0
1,2,1,10051,1,59.99,2015-07-28,0.11,HARDERSFIELD,Baker County,8300.0
2,3,1,10058,1,13.99,2015-07-02,0.11,HARDERSFIELD,Baker County,8300.0
3,4,1,10058,1,13.99,2015-07-04,0.11,HARDERSFIELD,Baker County,8300.0
4,5,1,10058,1,13.99,2015-07-06,0.11,HARDERSFIELD,Baker County,8300.0
...,...,...,...,...,...,...,...,...,...,...
12697909,12697910,9,966,2,20.99,2016-06-26,1.57,BLACKPOOL,Wallace County,7000.0
12697910,12697911,9,966,1,20.99,2016-06-29,0.79,BLACKPOOL,Wallace County,7000.0
12697911,12697912,9,984,1,25.99,2016-06-08,0.79,BLACKPOOL,Wallace County,7000.0
12697912,12697913,9,984,2,25.99,2016-06-17,1.57,BLACKPOOL,Wallace County,7000.0
12697913,12697914,9,984,1,25.99,2016-06-20,0.79,BLACKPOOL,Wallace County,7000.0

In [ ]:
#4) Sales*quantity = revenue per transaction
Store_CitySales['Revenue'] = Store_CitySales['SalesPrice'] * Store_CitySales['SalesQuantity']

tSales_Summary = (Store_CitySales.groupby('City').agg(totalRevenue = ('Revenue', 'sum')))

In [ ]:
final = pd.merge(cityStores, cityEmployees, on='City', how = 'left')

final = pd.merge(final, Store_CitySales, on='City', how = 'left')

display(final)